select
    product_id,
    product_category_name,
    product_name_length,
    product_description_length,
    product_photos_qty,
    product_weight_g,
    product_length_cm,
    product_height_cm,
    product_width_cm,
    _source_lsn,
    _source_ts,
    _is_deleted,
    product_category_name_english,
    _silver_loaded_at,
    valid_from,
    valid_to,
    is_current
from {{ source('silver', 'products') }}
